// Language translations for the application
const translations = {
  en: {
    // Login & Signup
    login: 'Login',
    signup: 'Sign Up',
    username: 'Username',
    password: 'Password',
    email: 'Email',
    selectLanguage: 'Select Language',
    english: 'English',
    kannada: 'ಕನ್ನಡ',
    hindi: 'हिंदी',
    loginButton: 'Login',
    signupButton: 'Sign Up',
    forgotPassword: 'Forgot Password?',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    invalidCredentials: 'Invalid username or password',
    loginSuccess: 'Login successful!',
    signupSuccess: 'Account created successfully!',
    
    // Complaint Form
    submitComplaint: 'Submit a Complaint',
    complaintTitle: 'Complaint Title',
    description: 'Description',
    category: 'Category',
    priority: 'Priority',
    selectCategory: 'Select Category',
    infrastructure: 'Infrastructure',
    sanitation: 'Sanitation',
    traffic: 'Traffic',
    safety: 'Safety',
    utilities: 'Utilities',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    critical: 'Critical',
    submitButton: 'Submit Complaint',
    submitting: 'Submitting...',
    complaintSubmitted: 'Complaint submitted successfully!',
    photoEvidence: 'Photo Evidence',
    takePhoto: 'Take Photo',
    uploadPhoto: 'Upload Photo',
    takePhotoDesc: 'Opens webcam to capture new photo',
    uploadPhotoDesc: 'Select existing photo from device',
    or: 'OR',
    
    // Citizen History
    myComplaintHistory: 'My Complaint History',
    complaintDetails: 'Complaint Details',
    evidencePhoto: 'Evidence Photo',
    resolutionProof: 'Resolution Proof',
    beforeImage: 'Before',
    afterImage: 'After',
    resolutionNotes: 'Resolution Notes',
    submittedOn: 'Submitted On',
    feedback: 'Feedback',
    giveFeedback: 'Give Feedback',
    feedbackSubmitted: 'Feedback Submitted',
    rating: 'Rating',
    comments: 'Comments (optional)',
    shareExperience: 'Share your experience...',
    submitFeedback: 'Submit Feedback',
    viewOnMaps: 'View on Google Maps',
    noComplaints: 'No complaints found. Submit your first complaint!',
    
    // Predict Category & Priority
    autoDetectedInformation: 'Auto-Detected Information',
    detectedIssue: 'Detected Issue',
    categoryLabel: 'CATEGORY',
    priorityLabel: 'PRIORITY',
    confidenceLabel: 'CONFIDENCE',
    predictButton: 'Predict',
    predicting: 'Predicting...',
    
    // Dashboard
    dashboard: 'Dashboard',
    myComplaints: 'My Complaints',
    notifications: 'Notifications',
    profile: 'Profile',
    logout: 'Logout',
    status: 'Status',
    submitted: 'Submitted',
    inProgress: 'In Progress',
    resolved: 'Resolved',
    rejected: 'Rejected',
    
    // Keywords for Category Detection
    pothole: 'Pothole',
    road: 'Road',
    garbage: 'Garbage',
    water: 'Water',
    leak: 'Leak',
    damage: 'Damage',
    broken: 'Broken',
    accident: 'Accident',
    traffic: 'Traffic',
    infrastructure: 'Infrastructure',
    street: 'Street',
    hole: 'Hole',
    debris: 'Debris',
    litter: 'Litter',
    smoke: 'Smoke',
    fire: 'Fire',
    waste: 'Waste',
    trash: 'Trash',
    dirty: 'Dirty',
    sewage: 'Sewage',
    dump: 'Dump',
    filth: 'Filth',
    sidewalk: 'Sidewalk',
    pavement: 'Pavement',
    crack: 'Crack',
    bridge: 'Bridge',
    building: 'Building',
    streetlight: 'Streetlight',
    light: 'Light',
    surface: 'Surface',
    signal: 'Signal',
    congestion: 'Congestion',
    vehicle: 'Vehicle',
    car: 'Car',
    collision: 'Collision',
    blocked: 'Blocked',
    sign: 'Sign',
    marking: 'Marking',
    intersection: 'Intersection',
    injury: 'Injury',
    emergency: 'Emergency',
    danger: 'Danger',
    hazard: 'Hazard',
    unsafe: 'Unsafe',
    threat: 'Threat',
    exposed: 'Exposed',
    collapsed: 'Collapsed',
    electricity: 'Electricity',
    power: 'Power',
    gas: 'Gas',
    outage: 'Outage',
    pole: 'Pole',
    wire: 'Wire',
    supply: 'Supply',
    leakage: 'Leakage',
    leaking: 'Leaking',
    drainage: 'Drainage',
    pipeline: 'Pipeline',
    
    // Common
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
  },
  kn: {
    // Login & Signup
    login: 'ಲಾಗಿನ್',
    signup: 'ಸೈನ್ ಅಪ್',
    username: 'ಬಳಕೆದಾರ ಹೆಸರು',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    email: 'ಇಮೇಲ್',
    selectLanguage: 'ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ',
    english: 'English',
    kannada: 'ಕನ್ನಡ',
    hindi: 'हिंदी',
    loginButton: 'ಲಾಗಿನ್',
    signupButton: 'ಸೈನ್ ಅಪ್',
    forgotPassword: 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಿ?',
    noAccount: 'ಖಾತೆ ಇಲ್ಲವೇ?',
    haveAccount: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
    invalidCredentials: 'ಅಮಾನ್ಯ ಬಳಕೆದಾರ ಹೆಸರು ಅಥವಾ ಪಾಸ್‌ವರ್ಡ್',
    loginSuccess: 'ಲಾಗಿನ್ ಯಶಸ್ವಿ!',
    signupSuccess: 'ಖಾತೆ ಯಶಸ್ವಿಯಾಗಿ ರಚಿಸಲಾಗಿದೆ!',
    
    // Complaint Form
    submitComplaint: 'ಅಸಮಾಧಾನ ಸಲ್ಲಿಸಿ',
    complaintTitle: 'ಅಸಮಾಧಾನದ ಶೀರ್ಷಿಕೆ',
    description: 'ವಿವರಣೆ',
    category: 'ವರ್ಗ',
    priority: 'ಆದ್ಯತೆ',
    selectCategory: 'ವರ್ಗ ಆಯ್ಕೆ ಮಾಡಿ',
    infrastructure: 'ಮೂಲಸೌಕರ್ಯ',
    sanitation: 'ನೈರ್ಮಲ್ಯ',
    traffic: 'ಟ್ರಾಫಿಕ್',
    safety: 'ಸುರಕ್ಷತೆ',
    utilities: 'ಸೇವೆಗಳು',
    low: 'ಕಡಿಮೆ',
    medium: 'ಮಧ್ಯಮ',
    high: 'ಹೆಚ್ಚು',
    critical: 'ಸಂಕಟಕರ',
    submitButton: 'ಅಸಮಾಧಾನ ಸಲ್ಲಿಸಿ',
    submitting: 'ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...',
    complaintSubmitted: 'ಅಸಮಾಧಾನ ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ!',
    photoEvidence: 'ಫೋಟೋ ಪುರಾವೆ',
    takePhoto: 'ಫೋಟೋ ತೆಗೆದುಕೊಳ್ಳಿ',
    uploadPhoto: 'ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    takePhotoDesc: 'ಹೊಸ ಫೋಟೋ ಕ್ಯಾಪ್ಚರ್ ಮಾಡಲು ವೆಬ್‌ಕ್ಯಾಮ್ ತೆರೆಯುತ್ತದೆ',
    uploadPhotoDesc: 'ಸಾಧನದಿಂದ ಅಸ್ತಿತ್ವದ ಫೋಟೋ ಆಯ್ಕೆ ಮಾಡಿ',
    or: 'ಅಥವಾ',
    
    // Citizen History
    myComplaintHistory: 'ನನ್ನ ಅಸಮಾಧಾನದ ಇತಿಹಾಸ',
    complaintDetails: 'ಅಸಮಾಧಾನದ ವಿವರಗಳು',
    evidencePhoto: 'ಪುರಾವೆ ಫೋಟೋ',
    resolutionProof: 'ಪರಿಹಾರ ಪುರಾವೆ',
    beforeImage: 'ಮೊದಲು',
    afterImage: 'ನಂತರ',
    resolutionNotes: 'ಪರಿಹಾರ ಟಿಪ್ಪಣಿಗಳು',
    submittedOn: 'ಸಲ್ಲಿಸಿದ ದಿನಾಂಕ',
    feedback: 'ಪ್ರತಿಕ್ರಿಯೆ',
    giveFeedback: 'ಪ್ರತಿಕ್ರಿಯೆ ನೀಡಿ',
    feedbackSubmitted: 'ಪ್ರತಿಕ್ರಿಯೆ ಸಲ್ಲಿಸಲಾಗಿದೆ',
    rating: 'ರೇಟಿಂಗ್',
    comments: 'ಕಾಮೆಂಟ್‌ಗಳು (ಐಚ್ಛಿಕ)',
    shareExperience: 'ನಿಮ್ಮ ಅನುಭವ ಹಂಚಿಕೊಳ್ಳಿ...',
    submitFeedback: 'ಪ್ರತಿಕ್ರಿಯೆ ಸಲ್ಲಿಸಿ',
    viewOnMaps: 'ಗೂಗಲ್ ಮ್ಯಾಪ್‌ನಲ್ಲಿ ವೀಕ್ಷಿಸಿ',
    noComplaints: 'ಯಾವುದೇ ಅಸಮಾಧಾನ ಕಂಡುಬಂದಿಲ್ಲ. ನಿಮ್ಮ ಮೊದಲ ಅಸಮಾಧಾನ ಸಲ್ಲಿಸಿ!',
    
    // Predict Category & Priority
    autoDetectedInformation: 'ಸ್ವಯಂ-ಪತ್ತೆ ಮಾಡಿದ ಮಾಹಿತಿ',
    detectedIssue: 'ಪತ್ತೆ ಮಾಡಿದ ಸಮಸ್ಯೆ',
    categoryLabel: 'ವರ್ಗ',
    priorityLabel: 'ಆದ್ಯತೆ',
    confidenceLabel: 'ವಿಶ್ವಾಸ',
    predictButton: 'ಊಹೆ ಮಾಡಿ',
    predicting: 'ಊಹೆ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    predictCategory: 'ವರ್ಗ ಊಹೆ ಮಾಡಿ',
    predictPriority: 'ಆದ್ಯತೆ ಊಹೆ ಮಾಡಿ',
    categoryPredicted: 'ವರ್ಗ ಊಹೆ ಮಾಡಲಾಗಿದೆ',
    priorityPredicted: 'ಆದ್ಯತೆ ಊಹೆ ಮಾಡಲಾಗಿದೆ',
    predictDescription: 'ಶೀರ್ಷಿಕೆ ಮತ್ತು ವಿವರಣೆ ಆಧಾರದ ಮೇಲೆ',
    suggestedCategory: 'ಸೂಚಿತ ವರ್ಗ',
    suggestedPriority: 'ಸೂಚಿತ ಆದ್ಯತೆ',
    confidence: 'ವಿಶ್ವಾಸ',
    acceptSuggestion: 'ಸ್ವೀಕರಿಸಿ',
    rejectSuggestion: 'ನಿರಾಕರಿಸಿ',
    
    // Dashboard
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    myComplaints: 'ನನ್ನ ಅಸಮಾಧಾನಗಳು',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    profile: 'ಪ್ರೊಫೈಲ್',
    logout: 'ಲಾಗ್ ಔಟ್',
    status: 'ಸ್ಥಿತಿ',
    submitted: 'ಸಲ್ಲಿಸಲಾಗಿದೆ',
    inProgress: 'ಪ್ರಗತಿಯಲ್ಲಿ',
    resolved: 'ಪರಿಹರಿಸಲಾಗಿದೆ',
    rejected: 'ನಿರಾಕರಿಸಲಾಗಿದೆ',
    
    // Keywords for Category Detection
    pothole: 'ಗುಂಡಿ',
    road: 'ರಸ್ತೆ',
    garbage: 'ಕಸ',
    water: 'ನೀರು',
    leak: 'ಸೋರಿಕೆ',
    damage: 'ಹಾನಿ',
    broken: 'ಮುರಿದ',
    accident: 'ಅಪಘಾತ',
    traffic: 'ಟ್ರಾಫಿಕ್',
    infrastructure: 'ಮೂಲಸೌಕರ್ಯ',
    street: 'ಬೀದಿ',
    hole: 'ರಂಧ್ರ',
    debris: 'ಅವಶೇಷ',
    litter: 'ಕಸ',
    smoke: 'ಹೊಗೆ',
    fire: 'ಬೆಂಕಿ',
    waste: 'ತ್ಯಾಜ್ಯ',
    trash: 'ಕಸ',
    dirty: 'ಕೊಳೆಯ',
    sewage: 'ಮಲ',
    dump: 'ಸಾಗರ',
    filth: 'ಮಲಿನತೆ',
    sidewalk: 'ಪಾದಚಾರಿ ಮಾರ್ಗ',
    pavement: 'ಸಿಮೆಂಟ್ ಮಾರ್ಗ',
    crack: 'ಬಿರುಕು',
    bridge: 'ಸೇತುವೆ',
    building: 'ಕಟ್ಟಡ',
    streetlight: 'ರಸ್ತೆ ದೀಪ',
    light: 'ದೀಪ',
    surface: 'ಮೇಲ್ಮೈ',
    signal: 'ಸಂಕೇತ',
    congestion: 'ಸಂಚಯ',
    vehicle: 'ವಾಹನ',
    car: 'ಕಾರು',
    collision: 'ಘರ್ಷಣೆ',
    blocked: 'ನಿರ್ಬಂಧಿತ',
    sign: 'ಚಿಹ್ನೆ',
    marking: 'ಗುರುತು',
    intersection: 'ಛೇದಕ',
    injury: 'ಗಾಯ',
    emergency: 'ತುರ್ತು',
    danger: 'ಅಪಾಯ',
    hazard: 'ಅಪಾಯ',
    unsafe: 'ಅಸುರಕ್ಷಿತ',
    threat: 'ಬೆದರಿಕೆ',
    exposed: 'ಬಹಿರಂಗ',
    collapsed: 'ಕುಸಿತ',
    electricity: 'ವಿದ್ಯುತ್',
    power: 'ಶಕ್ತಿ',
    gas: 'ಅನಿಲ',
    outage: 'ಕಡಿತ',
    pole: 'ಕಂಬ',
    wire: 'ತಾರ',
    supply: 'ಸರಬರಾಜು',
    leakage: 'ಸೋರಿಕೆ',
    leaking: 'ಸೋರುತ್ತಿರುವ',
    drainage: 'ಒಳಚರಂಡಿ',
    pipeline: 'ಪೈಪ್ ಲೈನ್',
    
    // Common
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    error: 'ದೋಷ',
    success: 'ಯಶಸ್ವಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    save: 'ಉಳಿಸಿ',
    delete: 'ಅಳಿಸಿ',
    edit: 'ಸಂಪಾದಿಸಿ',
    close: 'ಮುಚ್ಚಿ',
    back: 'ಹಿಂದೆ',
    next: 'ಮುಂದೆ',
    previous: 'ಹಿಂದಿನ',
  },
  hi: {
    // Login & Signup
    login: 'लॉगिन',
    signup: 'साइन अप',
    username: 'उपयोगकर्ता नाम',
    password: 'पासवर्ड',
    email: 'ईमेल',
    selectLanguage: 'भाषा चुनें',
    english: 'English',
    kannada: 'ಕನ್ನಡ',
    hindi: 'हिंदी',
    loginButton: 'लॉगिन',
    signupButton: 'साइन अप',
    forgotPassword: 'पासवर्ड भूल गए?',
    noAccount: 'खाता नहीं है?',
    haveAccount: 'पहले से खाता है?',
    invalidCredentials: 'अमान्य उपयोगकर्ता नाम या पासवर्ड',
    loginSuccess: 'लॉगिन सफल!',
    signupSuccess: 'खाता सफलतापूर्वक बनाया गया!',
    
    // Complaint Form
    submitComplaint: 'शिकायत दर्ज करें',
    complaintTitle: 'शिकायत का शीर्षक',
    description: 'विवरण',
    category: 'श्रेणी',
    priority: 'प्राथमिकता',
    selectCategory: 'श्रेणी चुनें',
    infrastructure: 'बुनियादी ढांचा',
    sanitation: 'स्वच्छता',
    traffic: 'ट्रैफिक',
    safety: 'सुरक्षा',
    utilities: 'उपयोगिताएं',
    low: 'कम',
    medium: 'मध्यम',
    high: 'उच्च',
    critical: 'गंभीर',
    submitButton: 'शिकायत दर्ज करें',
    submitting: 'दर्ज किया जा रहा है...',
    complaintSubmitted: 'शिकायत सफलतापूर्वक दर्ज की गई!',
    photoEvidence: 'फोटो सबूत',
    takePhoto: 'फोटो लें',
    uploadPhoto: 'फोटो अपलोड करें',
    takePhotoDesc: 'नई फोटो कैप्चर करने के लिए वेबकैम खोलता है',
    uploadPhotoDesc: 'डिवाइस से मौजूदा फोटो चुनें',
    or: 'या',
    
    // Citizen History
    myComplaintHistory: 'मेरा शिकायत इतिहास',
    complaintDetails: 'शिकायत विवरण',
    evidencePhoto: 'सबूत फोटो',
    resolutionProof: 'समाधान सबूत',
    beforeImage: 'पहले',
    afterImage: 'बाद में',
    resolutionNotes: 'समाधान नोट्स',
    submittedOn: 'दर्ज की गई तारीख',
    feedback: 'प्रतिक्रिया',
    giveFeedback: 'प्रतिक्रिया दें',
    feedbackSubmitted: 'प्रतिक्रिया सबमिट की गई',
    rating: 'रेटिंग',
    comments: 'टिप्पणियां (वैकल्पिक)',
    shareExperience: 'अपना अनुभव साझा करें...',
    submitFeedback: 'प्रतिक्रिया सबमिट करें',
    viewOnMaps: 'गूगल मैप्स पर देखें',
    noComplaints: 'कोई शिकायत नहीं मिली। अपनी पहली शिकायत दर्ज करें!',
    
    // Predict Category & Priority
    autoDetectedInformation: 'स्वचालित रूप से पहचाना गया जानकारी',
    detectedIssue: 'पहचाना गया मुद्दा',
    categoryLabel: 'श्रेणी',
    priorityLabel: 'प्राथमिकता',
    confidenceLabel: 'आत्मविश्वास',
    predictButton: 'भविष्यवाणी करें',
    predicting: 'भविष्यवाणी की जा रही है...',
    predictCategory: 'श्रेणी की भविष्यवाणी करें',
    predictPriority: 'प्राथमिकता की भविष्यवाणी करें',
    categoryPredicted: 'श्रेणी की भविष्यवाणी की गई',
    priorityPredicted: 'प्राथमिकता की भविष्यवाणी की गई',
    predictDescription: 'शीर्षक और विवरण के आधार पर',
    suggestedCategory: 'सुझाई गई श्रेणी',
    suggestedPriority: 'सुझाई गई प्राथमिकता',
    confidence: 'आत्मविश्वास',
    acceptSuggestion: 'स्वीकार करें',
    rejectSuggestion: 'अस्वीकार करें',
    
    // Dashboard
    dashboard: 'डैशबोर्ड',
    myComplaints: 'मेरी शिकायतें',
    notifications: 'सूचनाएं',
    profile: 'प्रोफाइल',
    logout: 'लॉग आउट',
    status: 'स्थिति',
    submitted: 'दर्ज की गई',
    inProgress: 'प्रगति में',
    resolved: 'हल किया गया',
    rejected: 'अस्वीकृत',
    
    // Keywords for Category Detection
    pothole: 'गड्ढा',
    road: 'सड़क',
    garbage: 'कचरा',
    water: 'पानी',
    leak: 'रिसाव',
    damage: 'नुकसान',
    broken: 'टूटा हुआ',
    accident: 'दुर्घटना',
    traffic: 'ट्रैफिक',
    infrastructure: 'बुनियादी ढांचा',
    street: 'सड़क',
    hole: 'छेद',
    debris: 'मलबा',
    litter: 'कचरा',
    smoke: 'धुआं',
    fire: 'आग',
    waste: 'अपशिष्ट',
    trash: 'कचरा',
    dirty: 'गंदा',
    sewage: 'सीवेज',
    dump: 'डंप',
    filth: 'गंदगी',
    sidewalk: 'फुटपाथ',
    pavement: 'फुटपाथ',
    crack: 'दरार',
    bridge: 'पुल',
    building: 'भवन',
    streetlight: 'सड़क की रोशनी',
    light: 'प्रकाश',
    surface: 'सतह',
    signal: 'संकेत',
    congestion: 'भीड़',
    vehicle: 'वाहन',
    car: 'कार',
    collision: 'टकराव',
    blocked: 'अवरुद्ध',
    sign: 'संकेत',
    marking: 'निशान',
    intersection: 'चौराहा',
    injury: 'चोट',
    emergency: 'आपातकाल',
    danger: 'खतरा',
    hazard: 'खतरा',
    unsafe: 'असुरक्षित',
    threat: 'धमकी',
    exposed: 'उजागर',
    collapsed: 'ढहा हुआ',
    electricity: 'बिजली',
    power: 'शक्ति',
    gas: 'गैस',
    outage: 'कटौती',
    pole: 'खंभा',
    wire: 'तार',
    supply: 'आपूर्ति',
    leakage: 'रिसाव',
    leaking: 'रिसाव',
    drainage: 'जल निकासी',
    pipeline: 'पाइपलाइन',
    
    // Common
    loading: 'लोड हो रहा है...',
    error: 'त्रुटि',
    success: 'सफल',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    close: 'बंद करें',
    back: 'पीछे',
    next: 'अगला',
    previous: 'पिछला',
  }
};

// Language context service
export const languageService = {
  // Get translation for a key
  t: (key, language = 'en') => {
    return translations[language]?.[key] || translations['en'][key] || key;
  },

  // Get all translations for a language
  getTranslations: (language = 'en') => {
    return translations[language] || translations['en'];
  },

  // Get available languages
  getAvailableLanguages: () => [
    { code: 'en', name: 'English', nativeName: 'English' },
    { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
    { code: 'hi', name: 'Hindi', nativeName: 'हिंदी' }
  ],

  // Save language preference to localStorage
  setLanguage: (language) => {
    localStorage.setItem('preferredLanguage', language);
  },

  // Get saved language preference
  getLanguage: () => {
    return localStorage.getItem('preferredLanguage') || 'en';
  }
};
